# Generated by Django 5.0.6 on 2024-08-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('country', models.CharField(default='India', max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='fashionproduct',
            name='product_type',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids'), ('fashion', 'Fashion'), ('gadget', 'Gadget'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='gadgetproduct',
            name='product_type',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids'), ('fashion', 'Fashion'), ('gadget', 'Gadget'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='kidsproduct',
            name='product_type',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids'), ('fashion', 'Fashion'), ('gadget', 'Gadget'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='menproduct',
            name='product_type',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids'), ('fashion', 'Fashion'), ('gadget', 'Gadget'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='womenproduct',
            name='product_type',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids'), ('fashion', 'Fashion'), ('gadget', 'Gadget'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
