# Generated by Django 5.0.6 on 2024-06-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='lname',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='register',
            name='phone_no',
            field=models.IntegerField(default=''),
        ),
    ]
