# Generated by Django 5.0.6 on 2024-06-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0004_menproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='menproduct',
            name='image1',
            field=models.ImageField(default='', upload_to='Menproducts/'),
        ),
        migrations.AddField(
            model_name='menproduct',
            name='image2',
            field=models.ImageField(default='', upload_to='Menproducts/'),
        ),
        migrations.AlterField(
            model_name='menproduct',
            name='image',
            field=models.ImageField(default='', upload_to='Menproducts/'),
        ),
    ]
