# Generated by Django 5.0.6 on 2024-06-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0007_kidsproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='FashionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discription', models.CharField(default='', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(default='', upload_to='Menproducts/')),
                ('image1', models.ImageField(default='', upload_to='Menproducts/')),
                ('image2', models.ImageField(default='', upload_to='Menproducts/')),
            ],
        ),
    ]
